UNIT ZoomPlayerCodes;

INTERFACE

IMPLEMENTATION

BEGIN

(*

[ Zoom Player Command & Control interface ]
 ---------------------------------------------------------------------------------------------------------------------

 *** Introduction:
 Zoom Player supports multiple Command & Control interfaces:

 1. TCP/IP based Command and Control.
        Allows Command and Control of Zoom Player over an Internet or Intranet connection with full notification of the player's state.

 2. Inter-Process Win32 API Bi-Directional Command and Control.
        An external application registers its window with Zoom Player by calling a specially crafted WinAPI "SendMessage" command.  Once the application window is
        registered, the application can send Zoom Player control commands using the "SendMessage" WinAPI command and receive messages by capturing a special WinAPI message
        generated by Zoom Player and sent to the registered window.

 3. Simplified Inter-Process Win32 Control.
        A subset of commands that provide easy control over a limited subset of Zoom Player features.

 4. Command Line Interface.
        Control Zoom Player through the command line, requiring no programming experience whatsoever.

 *** TCP/IP based Command and Control:
 To use the TCP/IP interface, you must first enable it in the options dialog under "Advanced Options / System". The default TCP/IP port is "4769", this value can be altered
 on the same options dialog page. Alternatively, with Zoom Player v8.1 or newer, you can instruct Zoom Player to connect to your server using the "/CONNECTTCP:[address or
 ip]:[port]", for example "/CONNECTTCP:127.0.0.1:4770".

 When using the TCP/IP interface, the event number is always sent and returned as a 4-digit code followed by the event's content (when applicable). All content is string
 based and UTF-8 encoded to preserve country specific character codes.

 When sending TCP/IP commands, make sure to terminate each command with CRLF (ASCII #13#10).


 *** Inter-Process Win32 API Bi-Directional Command and Control:
 To register your application with Zoom Player, send Zoom Player (using the WinAPI "SendMessage" function) an ATOM String containing your application's window name and the
 following parameters (in the "SendMessage" function):

 WParam          : ATOM String value created using the WinAPI "GlobalAddAtom" function.
 LParam          : A value of "200" indicating that your application is trying to register itself.
 Message Number : WM_APP + 49.

 Your application must now capture the "WM_APP+444" WinAPI message which Zoom Player uses to send information to your application's window.  When Zoom Player notifies your
 application, the Zoom Player API event number (see below) is returned in the "WParam" value and the message content is returned in the "LParam" value.

 If the LParam value contain a string, it is stored as an ATOM String which your application must free using the WinAPI "GlobalDeleteAtom" function.



 *** Generated Events (Events generated by Zoom Player and sent to your application):
 [WParam]                                         | [LParam]
 -------------------------------------+----------------------------------------------
 0000 - Application Name                          | String describing the Application
 0001 - Application Version                       | String with the version text
 0100 - Ping                                      | Result of a call to message 0100, indicating the player is responsive
 1000 - State Change                              | 0  - Closed
                                                    1  - Stopped (doesn't apply to DVD, DVD Stop = Closed)
                                                    2  - Paused
                                                    3  - Playing
 1010 - Current Fullscreen State                  | 0  - Windowed
                                                    1  - Fullscreen
 1020 - Current FastForward State                 | 0  - Disabled
                                                    1  - Enabled
 1021 - Current Rewind State                      | 0  - Disabled
                                                    1  - Enabled
 1090 - Timeline Text                             | The current timeline text
 1100 - Position update                           | String containing media [Position / Duration],
                                                    For example: 00:00:12 / 01:02:35
 1110 - Current Duration                          | Current Duration in milliseconds
 1120 - Current Position                          | Current Position in milliseconds
 1130 - Current Frame Rate (realtime)             | Current Realtime Frame Rate in Frames per second (FPS). Only works with DirectShow based content playback
 1140 - Estimated Frame Rate                      | Estimated Frame Rate in Frames Per Second (FPS).
                                                    Note, some formats don't have a frame rate so the returned value is an estimate.
 1200 - OSD Message                               | String containing the OSD message
 1201 - OSD Message Off                           | No value, message just tells that the OSD window has disappeared
 1300 - Current Play Mode                         | 0  - DVD Mode
                                                    1  - Media Mode
                                                    2  - Audio Mode
 1310 - TV/PC Mode                                | 0  - PC Mode
                                                    1  - TV Mode (unused)
 1400 - DVD Title Change                          | Current Title
 1401 - DVD Title Count                           | Number of Titles
 1410 - DVD Domain Change                         | See EC_DVD_DOMAIN_CHANGE in DirectX SDK
 1420 - DVD Menu Mode                             | 0  - Not in a Menu
                                                    1  - In a Menu
 1450 - DVD Unique String                         | Returns a unique DVD indentifer
 1500 - DVD Chapter Change                        | Current Chapter
 1501 - DVD Chapter Count                         | Number of Chapters
 1600 - DVD/Media Active Audio Track              | Current Audio Track Index
 1601 - DVD/Media Audio Track Count               | Number of Audio Tracks
 1602 - DVD Audio Name                            | Contains the name of the Audio track and a padded number for example "001 5.1 AC3"
 1700 - DVD/Media Active Sub                      | Current Subtitle Track
 1701 - DVD/Media Sub Count                       | Number of Subtitle Tracks
 1702 - DVD Sub Name                              | Contains the name of the Subtitle track and a padded number for example "001 5.1 AC3"
 1704 - DVD Sub Disabled                          | 0 - Sub Visible
                                                    1 - Sub Hidden
 1750 - DVD Angle Change                          | Current Angle
 1751 - DVD Angle Count                           | Number of Angles in the DVD Title
 1800 - Currently Loaded File                     | String containing file name
 1810 - Current Playlist                          | String containing the Zoom Player Playlist structure.  Each entry is separated by the ">" character and is further
                                                    sub-divided into additional sections in this structure:
                                                  | T .. |t - Title
                                                  | N .. |n - Name
                                                  | E .. |e - Extension
                                                  | D .. |d - Date
                                                  | S .. |s - Size
                                                  | P .. |p - Path
                                                  | R .. |r - Duration
                                                  | F .. |f - Forced Duration
                                                    It is possible addtional tags will be used in future version, so code safely.
 1811 - Playlist Count/Change                     | Triggered when the playlist is modified and returns the Number of items in updated Playlist.
 1855 - End of File                               | End of file has been reached
 1900 - File PlayList Pos                         | String containing file position in playlist
 1920 - Playlist Cleared Ack.                     | A notification that the playlist has been cleared
 1950 - A Play List file was removed              | String containing the file name
 2000 - Video Resolution                          | String containing the video resolution (if there is one)
 2100 - Video Frame Rate                          | String containing the video frame rate (if there is one)
 2200 - AR Change                                 | String containing the AR String (same as OSD message)
 2210 - DVD AR Mode Change                        | 0  - Unknown
                                                    1  - Full-Frame
                                                    2  - Letterbox
                                                    3  - Anamorphic
 2300 - Current Audio Volume                      | The current Audio Volume
 2400 - Media Content Tags                        | Returns Media Content Strings (ID3/APE/WMA/Etc... Tags)
 2500 - A CD/DVD Was Inserted                     | Returns path to drive the disc was inserted to
 2611 - Video Display Area X-Ofs                  | Integer Value
 2621 - Video Display Area Y-Ofs                  | Integer Value
 2631 - Video Display Area Width                  | Integer Value
 2641 - Video Display Area Height                 | Integer Value
 2700 - Play Rate Changed                         | In Media Mode the Fast Play/Slow Motion Rate. In DVD Mode the Fast Forward/Slow Motion/Rewind Rate. Value is play rate
                                                    multiplied by 1000. For example: A value of "1500" means a play rate of "1.5". If you call a function and get this
                                                    message with the play rate value unchanged, it means the function failed to change the play rate.
 2710 - Random Play State                         | 0 - Disabled
                                                    1 - Enabled
 3000 - ZP Error Message                          | String of error messsage.
                                                    Note that there can be multiple errors appearing in sequence, only the last error may be visible by the user.
 3100 - Nav Dialog Opened                         | A Navigator Dialog has opened
                                                     0 - Blanking Navigator
                                                     1 - Chapter Navigator
                                                     2 - Context Navigator
                                                     3 - File Navigator
                                                     4 - GoTo Navigator
                                                     5 - Media Library Navigator
                                                     6 - MouseWheel Navigator
                                                     7 - Color Control Navigator
                                                     8 - Playlist Navigator
                                                     9 - Resize Navigator
                                                    10 - Station Navigator
                                                    11 - Web URL Navigator
                                                    12 - Main Navigator
                                                    13 - Media Library Selection Navigator
                                                    14 - Virtual Keyboard Input Navigator
                                                    15 - Equalizer Navigator
                                                    16 - Station Navigator
                                                    17 - Confirmation Navigator
                                                    18 - Play History Navigator
                                                    19 - Navigation Style Navigator
                                                    20 - Download Navigator
                                                    21 - Information Navigator
 3110 - Nav Dialog Closed                        | A Navigator Dialog has closed (Values are the same as #3100)
 3200 - Screen Saver Mode                        | The ZP Screen Saver has:
                                                   0 - Started
                                                   1 - Ended
 4000 - Virtual Keyboard Input Result | This message contains 3 parameters separated by the "|" character.
                                                                                The first parameter contains a value of "0" (fail) or "1" (success).
                                                                                The second parameter contains the unique text identifier used in the initial 4000 call.  In
                                                                                the cases where the call was originated from within Zoom Player, the unique identifier is
                                                                                always prefixed by "vk", for example "vkRename". The third parameter contains the user
                                                                                entered UTF8 encoded text string.
 5100 - ZP Function Called                       | Value contains name of function
 5110 - ZP ExFunction Called                     | Value contains name of function
 5120 - ZP ScanCode Called                       | Value contains ScanCode.

 6000 - Shared Items List                        | Value contains a list of files and folder returned by the previous 6000 call.  The returned format is the same as
                                                   message 1810.
 6010 - Add Shared files ack.                    | This messages acknowledges that a call to message 6010 has finished processing.
 9000 - Flash Mouse Click                        | Used to indicate a screen position was clicked if when interactive flash mode is enabled.




 *** Controlling Zoom Player (Commands generated by an external process and sent to Zoom Player):
 The events listed below are only available when using the TCP/IP interface. Commands that contain parameters should be space separated, for example: "5100 fnPlay"

 When issuing a command that contains multiple parameters, a comma is used to separate the parameters, for example, "5110 exSetAR,1".

 -------------------------------------+-------------------------------------------------------------------------------
 0000 - Get Application Name                     | Returns 0000 message
 0001 - Get Version                              | Returns 0001 message
 0100 - Ping                                     | Returns 0100 message
 1000 - Get Play State                           | Returns 1000 message
 1010 - Get Fullscreen State                     | Returns 1010 message
 1090 - Request Timeline Text                    | Returns 1090 message
 1100 - Set Timeline Updates (on/off)            | 0 - Stop   Media Position Update messages
                                                   1 - Start  Media Position Update messages
                                                   2 - Resend Media Position Update messages
 1110 - Get Current Duration                     | Returns 1110 message
 1120 - Get Current Position                     | Returns 1120 message
 1130 - Get Current Frame Rate (FPS)             | Returns 1130 message
 1140 - Get Estimated Frame Rate (FPS)           | Returns 1140 message
 1200 - Show a PopUp OSD Text                    | Parameter is a UTF8 encoded text to be shown as a PopUp OSD
 1201 - Temp Disable PopUp OSD                   | Temporarily Disables the PopUp OSD
 1202 - Re-Enable PopUp OSD                      | Re-Enables the PopUp OSD
 1210 - Set OSD "Visible" Duration               | Value in Seconds
 1300 - Get Play Mode                            | Returns 1300 message
 1400 - Request DVD Title                        | Returns 1400 message
 1401 - Request DVD Title Count                  | Returns 1401 message
 1420 - Request DVD Menu Mode                    | Returns 1420 message
 1450 - Request DVD Unique String                | Returns 1450 message
 1500 - Request DVD Chapter                      | Returns 1500 message
 1501 - Request DVD Chapter Count                | Returns 1501 message
 1600 - Request Audio Track                      | Returns 1600 message
 1601 - Request Audio Track Count                | Returns 1601 message
 1602 - Request DVD Audio Names                  | Returns 1602 message
 1603 - Set Audio Track                          | Set the active Audio Track.
                                                   Valid DVD values are 0-7 or 15 for default track
 1700 - Request Subtitle Index                   | Returns 1700 message
 1701 - Request Subtitle Count                   | Returns 1701 message
 1702 - Request DVD Subtitle Names               | Returns 1702 message
 1703 - Set Subtitle Track                       | Set the DVD's Subtitle Track.
                                                   Valid values 0-31, also enables subtitle
 1704 - Hide Subtitles                           | Disable Subtitles from showing
 1750 - Request DVD Angle                        | Returns 1750 message
 1751 - Request DVD Angle Count                  | Returns 1751 message
 1753 - Set DVD Angle                            | Set the DVD's Angle.
                                                   Valid Values 1-9
 1800 - Request Playing File Name                | Returns 1800 message
 1810 - Request Playlist                         | Returns 1810 message
 1811 - Request Playlist Count                   | Returns 1811 message
 1850 - Play File                                | Play a Media File, Value is a UTF8 encoded string containing the file name.
 1852 - Close Media File                         | Closes the playing media file or stops a DVD in DVD Mode.
 1860 - Browse Web                               | Browse a web page, Value is the web address (URL)
 1900 - Get Playlist Index                       | Returns 1900 message
 1910 - Set Playlist Index                       | Value from 0 to Number items in the playlist-1 (plays the file in index).
 1920 - Clear Playlist                           | Clears the Current Playlist (will close any playing file)
 1930 - Add Playlist File                        | Add a file to the Playlist
 1940 - Select Playlist Item                     | Select an Item in the Playlist Value from 0 to Number items in the playlist-1.
 1941 - DeSelect Playlist Item                   | Remove selection of a Playlist item Value from 0 to Number items in the playlist-1.
 1950 - Remove Playlist Item                     | Remove a Playlist item from the list Value from 0 to Number items in the playlist-1. Returns both an 1950 and 1900 message.
 2200 - Request AR Mode                          | Request the current ZP AR Mode
 2210 - Request DVD AR Mode                      | Request the DVD AR Mode (see outgoing #2210)
 2300 - Request Audio Volume                     | Request the Audio Volume Level
 2600 - Set Derived Mode Aspect Ratio            | Sets the aspect ratio used for Derived Aspect Ratio mode for the currentply playing video. The aspect ratio is specified
                                                   as: "Width Ratio"+"Height Ratio" left shifted 16 bits. For Example, 16:9 would be "16+9*65536" or "16+9<<16" or
                                                   "16+(9 shl 16)" (the examples do the same thing in a different syntax).
 2610 - Set Video Display Area X-Ofs             | Integer Value.
 2611 - Get Video Display Area X-Ofs             | Integer Value (Returns 2611 message).
 2620 - Set Video Display Area Y-Ofs             | Integer Value.
 2621 - Get Video Display Area Y-Ofs             | Integer Value (Returns 2621 message).
 2630 - Set Video Display Area Width             | Integer Value.
 2631 - Get Video Display Area Width             | Integer Value (Returns 2631 message).
 2640 - Set Video Display Area Height            | Integer Value.
 2641 - Get Video Display Area Height            | Integer Value (Returns 2641 message).
 2650 - Set Player Window dimensions             | Integer Values representing the Left,Top,Width,Height position of the player window.  For example: 50,50,800,600
 2660 - Set Player on-top value                  | 0 = Standard window mode
                                                   1 = Player window is on-top of other windows
 2670 - Set Fullscreen Monitor                   | 0 = Monitor where the player window is displayed
                                                   1 = Monitor #1
                                                   2 = Monitor #2
                                                   3 = Monitor #3...
 2700 - Get Play Rate                            | Returns 2700 message.
 2701 - Set Play Rate                            | Set the Media Mode Fast Play/Slow Motion rate or the DVD Mode Fast Forward/Slow Motion/ Rewind rate. Value is an integer
                                                   representing the play rate multiplied by 1000.  For example a value of "500" means a play rate of "0.5". Do not use
                                                   negative values in media mode, it will not work. Fast Play in media mode has a speed restriction a bit over "2.0" unless
                                                   Reclock is used as the audio renderer (this is a microsoft limitation due to sound driver architecture).
 2710 - Get Random Play Mode                     | Returns a 2710 message.
 3000 - Dismiss ZP Error                         | Close the ZP Error message (if visible).
 4000 - Virtual Keyboard Input Query             | Pop up the Virtual Keyboard interface to ask the user to input a text string. This message requires three UTF8 encoded
                                                   text string parameters. The first parameter indicates a unique identifier which is returned to you in the callback
                                                   message, which will help you identify which message prompted the user for input. The second parameter populates the text
                                                   entry field with the specified text (you can leave this empty if you want an empty text input value. The third parameter
                                                   is used to query the user for the type of input required. For example: "4000 eMail||Enter your eMail address" or to
                                                   include an existing text: "4000 eMail|no@one.org|Enter your eMail address" The result is returned in a 4000 message
                                                   indicating failure/success, the unique identfier and the text entered.  The entered text is returned even in the case
                                                   where the user selected to cancel the operation.
 5000 - Set Current Position                     | Sets the Current Play Position (in seconds.ms)
                                                 | For example "122.500" will seek to 2min:2sec.500ms
 5010 - Play DVD Title                           | Plays a DVD Title (depends on DVD Navigation accepting the title).
 5020 - Play DVD Title,Chapter                   | Same as 5010, Plays a DVD Title at a specific chapter, value of "1,5" plays Title #1, Chapter #5 (without the "" of
                                                   course).
 5030 - Play DVD Chapter                         | Same as 5010, Plays a DVD Chapter in the current Title.
 5100 - Call ZP Function                         | Calls a Zoom Player function by name (see skinning tutorial for list)
 5110 - Call ZP ExFunction                       | Calls a Zoom Player extended function by name (see skinning tutorial for list) Format "exFunctionName,Value"
 5120 - Call ZP ScanCode                         | Pass a keyboard scancode number to the Zoom Player Interpreter (such as VK_DOWN), this can be used to access the
                                                   Navigator interfaces, pass the scancode as a parameter.
 5130 - Call ZP nvFunction                       | Calls a Zoom Player navigation function by name (see skinning tutorial for list)
 6000 - List Shared Folder                       | Lists the content of the shared folder specified by the "/SharePath:[Path]" Command Line Parameter.  If no value is
                                                   specified, the root path is returned, if a path is specified, the content of the path (under the shared folder) is
                                                   returned.  Please note that for security reasons, paths can't begin with the ".", "/" or "\" character and may not
                                                   include any invalid character in the path's body (such as "|"). For Example: "6000 TV\Wednesday\" If the "/SharePath"
                                                   parameter is not specified, an empty message is returned.
 6010 - Add Shared files to Playlist             | Accept a list of file names separated by the "|" characters as the new playlist. The file names are appended to the end
                                                   of the playlist and a 6010 message is fired off to ackknowledge that processing has ended. The 'SharePath' value is
                                                   automatically added to the path of each file. For example: "6010 MyVideo.avi|MP3\MyAudio.mp3" With this example and
                                                   'SharePath' specified as "/SharePath:X:\Content\", Zoom Player will add the files to the playlist as:
                                                   X:\Content\MyVideo.avi X:\Content\MP3\MyAudio.mp3


 *** Simplified Inter-Process Win32 Control:

 Use the WinAPI "SendMessage" command to send Zoom Player a control command.  The values listed below are passed
 in the "LParam" field (the values are in HEX).

 The return value of the event contains an integer value with the current state (with the exception of
 "ZP_GetFileName" which returns an ATOM string containing the file name (make sure to deallocate the atom string).

   [ WinAPI Message Number : WM_APP + 50 ]
   ZP_GetFileName         = 0x1000; // Returns the Currently Playing file name
   ZP_GetDuration         = 0x1010; // Returns the playing media length
   ZP_GetPosition         = 0x1020; // Returns the current play position
   ZP_GetMode             = 0x1030; // Returns the current Play Mode (DVD, Media or Audio)
   ZP_GetState            = 0x1040; // Returns the current Play State (Closed, Stopped, Paused, Playing)
   ZP_GetPlayIndex        = 0x1050; // Returns the current (Playlist) Playing Item Index
   ZP_VolumeLevel         = 0x1060; // Returns the current Audio Volume Level
   ZP_SetPosition         = 0x5000; // Set current position (WParam specifies the value in Seconds)
   ZP_CallFunction        = 0x5010; // Call a Zoom Player function (WParam contains an ATOM string listing the function name).  The Function Names can be found here:
                                                                  // http://inmatrix.com/zplayer/highlights/zpfunctions.shtml
   ZP_CallExFunction      = 0x5020; // Call a Zoom Player extended function (WParam is an ATOM string listing the extended function name. The string should be listed as
                                     "[function],[value]", for example: "exSetAR,2" (don't include the "" in the string)

   [ WinAPI Message Number : WM_APP + 49 ]
   ZP_CallFunctionIndex   = 0x0000; // WParam holds a specific function number. The Function Numbers can be found here:
                                    // http://inmatrix.com/zplayer/highlights/zpfunctions.shtml
   ZP_ScanCode            = 0x0001; // WParam holds a keyboard scancode
   ZP_AltScanCode         = 0x0002; // WParam holds a keyboard scancode with ALT pressed
   ZP_CtrlScanCode        = 0x0003; // WParam holds a keyboard scancode with CTRL pressed
   ZP_ShiftScanCode       = 0x0004; // WParam holds a keyboard scancode with SHIFT pressed
   ZP_AltShiftScanCode    = 0x0005; // WParam holds a keyboard scancode with ALT+SHIFT pressed
   ZP_AltCtrlScanCode     = 0x0006; // WParam holds a keyboard scancode with ALT+CTRL pressed
   ZP_CtrlShiftScanCode   = 0x0007; // WParam holds a keyboard scancode with CTRL+SHIFT pressed
   ZP_ASCScanCode         = 0x0008; // WParam holds a keyboard scancode with ALT+SHIFT+CTRL pressed
   ZP_MWAction            = 0x0064; // WParam Value :
                                                                  // 0 = Mouse Middle Button Click
                                                                  // 1 = Mouse Wheel Up
                                                                  // 2 = Mouse Wheel Down

 Some functions require you to pass an ATOM string to Zoom Player.  Use the WinAPI "GlobalAddAtom" function to create
 the ATOM and pass it through the WParam parameter.  Zoom Player will clear any ATOM string it receives.



 *** Using the Command Line Interface:
 The Zoom Player command line interface is quite powerful and allows you to control the action without any
 programming experience.

 Some parameters can be used even if Zoom Player is already running as long as you are not running multiple instances
 of the player (other parameters only have an affect on the initial run).

 For the full command line parameter list, visit the Zoom Player on-line help at:
 http://inmatrix.com/zplayer/parameters.shtml



 *** License:
 The Zoom Player Communication and Control interface may only be used commercially under a direct license with
 Inmatrix LTD.

 All rights reserved Inmatrix LTD.

Standard Functions:
No.	Function	Mode	Description
000	fnPlay 	All	Starts playback and toggles between Play & Pause states.
001	fnPause 	All	Pauses video and frame advances when already paused.
002	fnStop 	Media	Stops playback and goes to the beginning of the video.
            DVD	Stops playback and closes DVD.
003	fnStopToFirst 	Media	Stop to First Item in a Playlist.
004	fnNextChapter 	Media	Go to Next Chapter (Internal or OGM), if no chapters are specified, advance to the next item in the Playlist.
 	 	                DVD	Open the Next Bookmark.
005	fnPrevChapter 	Media	Go to Previous Chapter (Internal or OGM), if no chapters are specified, go back to the previous item in the Playlist.
 	 	                DVD	Open the Previous Bookmark.
006	fnNextTrack 	Media	Go to the Next item on the Playlist
 	 	              DVD	Go to the Next Chapter.
007	fnPrevTrack 	Media	Go to the Previous item on the Playlist.
 	 	              DVD	Go to the Next Chapter.
008	fnNextFrame 	All	Frame Step Forward.
009	fnPrevFrame 	All	Frame Step Backward.
010	fnNextVid 	Media	Play the Next Video in the current directory.
011	fnPrevVid 	Media	Play the Previous Video in the current directory.
012	fnSkipForward 	All	Short seek forward a specified number of seconds (default 5sec).
013	fnSkipBackward 	All	Short seek backward a specified number of seconds (default 5sec).
014	fnJumpForward 	All	Medium seek forward a specified number of seconds (default 20sec).
015	fnJumpBackward 	All	Medium seek backward a specified number of seconds (default 20sec).
016	fnSeekForward 	All	Long seek forward a specified number of seconds (default 120sec = 2 minutes).
017	fnSeekBackward 	All	Long seek backward a specified number of seconds (default 120sec = 2 minutes).
018	fnFastForward 	All	Play in Fast Forward.
019	fnRewind 	All	Rewind Playback.
020	fnSlowMotion 	All	Play in Slow Motion.
021	fnHalfFF 	All	Half Fast forward speed.
022	fnHalfSM 	All	Half Slow Motion speed.
023	fnVolUp 	All	Increase Volume.
024	fnVolDown 	All	Decrease Volume.
025	fnMute 	All	Mute Volume (ON/OFF).
026	fnABRepeat 	All	Start, Stop and Cancel AB-Repeat.
027	fnPlayEndCycle 	All	Cycle through the "On Play Complete" values.
028	fnZoomAxis 	All	Toggles the Zoom Axis (used with Zoom-In / Zoom-Out).
029	fnZoomIn 	All	Zoom into video (enlarge video area).
030	fnZoomOut 	All	Zoom out of video (shrink video area).
031	fnZoomInWidth 	All	Stretch the video width.
032	fnZoomOutWidth 	All	Shrink the video width.
033	fnZoomInHeight 	All	Stretch the video height.
034	fnZoomOutHeight 	All	Shrink the video height.
035	fnZoom 	All	Go into Zoom Mode.
036	fnFullScreen 	All	Go Into Fullscreen Mode.
037	fnFitSource 	All	Resize video area to the original video source size.
038	fnMax 	All	Maximize user interface to cover work area or if in fullscreen maximize video area to cover screen.
039	fnMinimize 	All	Minimize the user interface.
040	fnARCycle 	All	Cycle through Aspect Ratio modes.
041	fnRevARCycle 	All	Reverse Cycle through Aspect Ratio modes.
042	fnBar 	All	Show / Hide the Control Bar.
043	fnOSD 	All	Turn the On Screen Display ON / OFF.
044	fnOpen 	All	Open File(s) for playback.
045	fnOpenDir 	All	Open a Directory for playback.
046	fnInfo 	All	Playback Information Dialog (some information on the playing media).
047	fnOptions 	All	Open the Options Dialog.
048	fnPresets 	All	Open the Video Position Preset Dialog.
049	fnPlayList 	All	Show / Hide the Playlist Editor.
050	fnChapter 	Media	Show / Hide the Chapter Editor.
 	             	DVD	Show / Hide the Bookmark Editor.
051	fnSkin 	All	Show / Hide the Skin Selection dialog.
052	fnKeyHelp 	All	Opens the Keyboard Shortcut Dialog (key list).
053	fnExit 	All	Exit application.
054	fnAddChapter 	Media	Add Current Position to the Chapter Editor.
 	                DVD	Save Current Position as a Bookmark.
055	fnSaveChapter 	Media	Save Chapter List.
056	fnDVDMode 	All	Switch between the Media and DVD Modes.
057	fnDVDRootMenu 	DVD	Go to the DVD's Root Menu.
058	fnDVDTitleMenu 	DVD	Go to the DVD's Title Menu.
059	fnDVDSubMenu 	DVD	Go to the DVD's Subtitle Menu.
060	fnDVDAudioMenu 	DVD	Go to the DVD's Audio Menu.
061	fnDVDAngleMenu 	DVD	Go to the DVD's Angle Menu.
062	fnDVDChapterMenu	DVD	Go to the DVD's Chapter Menu.
063	fnDVDMenuLeft 	DVD	Move left on a DVD Menu.
064	fnDVDMenuRight 	DVD	Move right on a DVD Menu.
065	fnDVDMenuUp 	DVD	Move up on a DVD Menu.
066	fnDVDMenuDown 	DVD	Move down on a DVD Menu.
067	fnDVDMenuSelect 	DVD	Activate selected DVD Menu item.
068	fnDVDCC 	All	Closed Captions ON / OFF.
069	fnDVDAngle 	Media	Cycle through OGM Video Tracks.
 	            	DVD	Cycle through DVD Angles.
070	fnDVDSub 	Media	Cycle through VobSub/OGM Subtitle Tracks.
 	          	DVD	Cycle through DVD Subtitle Tracks.
071	fnAudioTrack 	Media	Cycle through Media Audio Tracks.
              	 	DVD	Cycle through DVD Audio Tracks.
072	fnStayOnTop 	All	Stay On Top ON / OFF.
073	fnMPEG4 	All	MPEG4/DivX/Video Decoder Dialog (if filter is in use).
074	fnSub 	All	Open the Subtitle configuration dialog.
075	fnAudioFilter 	All	TFM/DeDynamic Audio Filter Dialog (if filter is in use).
076	fnIncRate 	All	Increase Play rate.
077	fnDecRate 	All	Decrease Play rate.
078	fnPrevFilterFile	None	Previous Manual Filter File ** disabled **
079	fnNextFilterFile	None	Next Manual Filter File ** disabled **
080	fnSaveDF 	All	Save Definition File for the currently open media.
081	fnFrameCapture 	All	Screenshot / Frame Capture.
082	fnPattern 	All	Cycle Pattern Modes.
083	fnEject 	All	Eject the specified CD drive.
084	fnOverlayControl	All	Show / Hide the Color Control Interface.
085	fnOverlayApply 	All	Apply the Color Controls (same as button in options).
086	fnOverlayReset 	All	Reset the Color Controls back to their default settings.
087	fnIncBrightness 	All	Increase Brightness.
088	fnDecBrightness 	All	Decrease Brightness.
089	fnIncContrast 	All	Increase Contrast.
090	fnDecContrast 	All	Decrease Contrast.
091	fnIncGamma 	All	Increase Gamma.
092	fnDecGamma 	All	Decrease Gamma.
093	fnIncHue 	All	Increase Hue.
094	fnDecHue 	All	Decrease Hue.
095	fnIncSaturation 	All	Increase Saturation.
096	fnDecSaturation 	All	Decrease Saturation.
097	fnUnpause 	All	Unpause the video (Discrete Play).
098	fnAddALBookmark 	DVD	Add DVD Auto-Load Bookmark.
099	fnSeekToStart 	All	Seek to start of Video.
100	fnAudioDecoder 	All	Pop the property dialog of filters with "Audio Decoder" in their titles.
101	fnDVDMenuPrev 	DVD	Return from DVD Sub-Menu. If on Top Menu then Resume playback.
102	fnChapterNav 	Media	Show / Hide the Chapter Navigator dialog.
 	              	DVD	Show / Hide the Bookmark Navigator dialog.
103	fnPlayListNav 	All	Show / Hide the Playlist Navigator dialog.
104	fnFileNav 	All	Show / Hide the File Navigator dialog.
105	fnBlankingNav 	All	Show / Hide the Blanking Navigator dialog.
106	fnBlankingPreset	All	Show / Hide the Blanking Presets dialog.
107	fnBlanking 	All	Show / Hide Video Blanking.
108	fnRandomPlay 	Media	Turns Random (shuffle) Play ON / OFF.
109	fnResizeNav 	All	Show / Hide the Resize Navigator dialog.
110	fnDisableDVDSub 	Media	Disable (hide) Subtitle display.
                  	 	DVD	Disable DVD Subtitle.
111	fnPresetCycle 	All	Cycle through Video Position Presets.
112	fnRevPresetCycle	All	Reverse Cycle through Video Position Presets.
113	fnBlankCycle 	All	Cycle through Blanking Position Presets.
114	fnRevBlankCycle 	All	Reverse Cycle through Blanking Position Presets.
115	fnDVDPlayStart 	DVD	Play DVD bypassing Auto-Bookmark loading features.
116	fnNextArrowFunc 	All	Next Active Arrow Control function.
117	fnPrevArrowFunc 	All	Previous Active Arrow Control function.
118	fnAutoARToggle 	DVD	Enable / Disable Automatic DVD Aspect Ratio.
119	fnFrameZeroALBM 	DVD	Attempt setting a DVD Auto-Load bookmark at frame zero.
120	fnPauseAtEOF 	Media	Pause Playback at end of currently playing file.
121	fnSceneCut 	All	Show / Hide the Scene Cut Editor.
122	fnGoTo 	All	Show / Hide the GoTo Timeline dialog.
123	fnGoToNav 	All	Show / Hide the GoTo Timeline Navigator interface.
124	fnMWFuncNav 	All	Show / Hide the Mouse Wheel Function Navigator interface.
125	fnLoop 	Media	Switch between Do Nothing and Auto Reply on Play Complete.
126	fnBalanceLeft 	All	Move Audio Balance to the Left.
127	fnBalanceRight 	All	Move Audio Balance to the Right.
128	fnOpenDrive 	All	Open an entire drive.
129	fnMediaNav 	All	Show / Hide the Media Library Navigator.
130	fnMediaPathEdit 	All	Show / Hide the Media Library Path and Category Editor.
131	fnSrcRelStretch 	All	Enable / Disable Source Relative User Interface Stretch.
132	fnZoom50 	All	Set video to default to 50%.
133	fnZoom100 	All	Set video to default to 100%.
134	fnZoom200 	All	Set video to default to 200%.
135	fnZoom400 	All	Set video to default to 400%.
136	fnZoom800 	All	Set video to default to 800%.
137	fnWebNav 	All	Show / Hide the Web URL Navigator.
138	fnBringToFront 	All	Bring Player Window to Front.
139	fnLoopPlay 	Media	Enable / Disable looping of currently playing track.
140	fnPLAddFiles 	All	Add Files to Playlist.
141	fnPLAddDir 	All	Add Directory to Playlist.
142	fnPLRemove 	All	Remove Selected Items from Playlist.
143	fnPLClear 	All	Clear the entire Playlist.
144	fnPLLoadList 	All	Load a Playlist.
145	fnPLSaveList 	All	Save the Playlist.
146	fnPLSort 	All	Sort the Playlist Items.
147	fnPLItemUp 	All	Move Selected Playlist Items Up.
148	fnPLItemDown 	All	Move Selected Playlist Items Down.
149	fnPLMax 	All	Maximize the Playlist Window.
150	fnLoadDF 	All	Load Definition File for the currently open media.
151	fnRadioManager 	Media	Show/Hide the Station Manager Dialog.
152	fnContextNav 	All	Show/Hide the Context Navigator.
153	fnPlayHistory 	Media	Show/Hide the Play History Interface.
154	fnPLGetDuration 	Media	Get Duration of Media Files in the current Playlist.
155	fnEqualizer 	All	Show/Hide the Internal Equalizer Window.
156	fnEQEditor 	All	Show/Hide the Equalizer Profile Selector/Editor.
157	fnEQReset 	All	Reset the current Equalizer Values.
158	fnEQToggle 	All	Enable/Disable the Equalizer.
159	fnResyncAhead 	All	Resynchronize Audio Ahead.
160	fnResyncBack 	All	Resynchronize Audio Back.
161	fnFastPlay 	Media	Fast Playback with Audio.
162	fnVobSubSelect 	All	DirectVobSub Subtitle File Selection.
163	fnOpenURL 	All	Open URL.
164	fnAudioMode 	Media	Switch to Audio only mode (no video area) skin.
165	fnSSaverToggle 	All	Internal Screen Saver Toggle.
166	fnTVMode 	None	Not implemented.
167	fnSpace 	All	Call the user-selected Space function.
168	fnIncHeight 	All	Increase Height 1 Pixel.
169	fnDecHeight 	All	Decrease Height 1 Pixel.
170	fnIncWidth 	All	Increase Width 1 Pixel.
171	fnDecWidth 	All	Decrease Width 1 Pixel.
172	fnDummy 	All	Does nothing, useful for skinning.
173	fnSceneCutToggle	All	Enable/Disable the Scene Cut feature.
174	fnStationNav 	All	Show/Hide the Station Navigator.
175	fnVidLeft 	All	Move Video Position to the Left.
176	fnVidRight 	All	Move Video Position to the Right.
177	fnVidUp 	All	Move Video Position Upwards.
178	fnVidDown 	All	Move Video Position Downwards.
179	fnPLItemDir 	All	Open the directory of the currently highlighted item in the Playlist.
180	fnDateTime 	All	OSD-Popup of the current Date & Time.
181	fnSubSyncAhead 	Media	(Only with DirectVobSub) Resynch Subtitles Ahead 100ms.
182	fnSubSyncBack 	Media	(Only with DirectVobSub) Resynch Subtitles Back 100ms.
183	fnSubUp 	Media	(Only with DirectVobSub) Move Subtitles Up 1 percent.
184	fnSubDown 	Media	(Only with DirectVobSub) Move Subtitles Down 1 percent.
185	fnPLControl 	All	Open/Close the Playlist Control interface.
186	fnPLMagToggle 	All	Toggle the Playlist Editor's Magnetic Docking.
187	fnEQMagToggle 	All	Toggle the Equalizer's Magnetic Docking.
188	fnIncPreAmp 	All	Increase PreAmp Volume.
189	fnDecPreAmp 	All	Decrease PreAmp Volume.
190	fnMainNav 	All	Show/Hide the Main Navigator.
191	fnLibCategoryNav	All	Show/Hide the Media Library Category Navigator.
192	fnPrevDirFileExt	Media	Play Previous file in the directory with the same File Extension.
193	fnNextDirFileExt	Media	Play Next file in the directory with the same File Extension.
194	fnCBarButToggle 	All	Show/Hide the Control Bar Buttons.
195	fnDeleteCurrent 	Media	Delete the Currently Playing file.
196	fnPLtoTop 	All	Move selected Playlist items to top of list.
197	fnPLtoBottom 	All	Move selected Playlist items to bottom of list.
198	fnEQNav 	All	Show/Hide the Equalizer Navigator.
199	fnPlayHistoryNav	All	Show/Hide the Play History Navigator.
200	fnCloseNavs 	All	Close All Navigators.
201	fnLastNav 	All	Open/Close the last open navigator.
202	fnPrevDVDTitle 	DVD	Go to Previous DVD Title.
203	fnNextDVDTitle 	DVD	Go to Next DVD Title.
204	fnContactSheet 	Media	Open the Contact Sheet dialog.
205	fnReloadCurrent 	Media	Reload the currently open media file.
206	fnBlankMonitors 	All	Blank (cover with a black window) non-Active monitors.
207	fnFSActMonitor 	All	Fullscreen on active monitor.
208	fnDownloadNav 	All	Download Manager Navigator (show/hide).
209	fnPosToClipboard	All	Copy the current position to the Windows Clipboard.
210	fnInfoNav 	All	Information Navigator (show/hide).
211	fnSaveFileAs 	All	Save currently playing file.
212	fnDoSearch 	All	Unused at this time.
213	fnSearchList 	All	Unused at this time.
214	fnDeInterlace 	All	DeInterlace Video (enabled/disabled).
215	fnSharpen 	All	Sharpen Video (enabled/disabled).
216	fnOpenWebPage 	All	Open Web Page Dialog.
217	fnRingTone 	All	Create a RingTone from a playing media section.
218	fnZoomTo43Wide 	All	Zoom on badly encoded 16:9 content (encoded with black bars).
219	fnVolumeWindow 	All	Pop-up the Volume-Slider Window.
220	fnWhiteWash 	All	WhiteWash Screen-Burn repair.
221	fnResetWindows 	All	Reset user interface windows to their default location.
222	fnIncRateEx 	All	Increase Play Rate by a user specified value.
223	fnDecRateEx 	All	Decrease Play Rate by a user specified value.
224	fnZoomInLevel 	All	Cycle Zoom-in Levels (16.6%, 33.3%, 50%, 100%).
225	fnSkinSelectNav 	All	Fullscreen navigation skin selection navigator (show/hide).
226	fnResetBright 	All	Reset Brightness to default value.
227	fnResetContrast 	All	Reset Contrast to default value.
228	fnResetGamma 	All	Reset Gamma to default value.
229	fnResetHue 	All	Reset Hue to default value.
230	fnResetSatur 	All	Reset Saturation to default value.
231	fnRandDirMedia 	Media	Random play a media file from the playing directory.
232	fnRandDirFileExt 	Media	Random play a file with the same extension from the playing directory.
233	fnSeekLongForward 	All	Long seek forward a specified number of seconds (default 600 seconds = 10 minutes).
234	fnSeekLongBackward	All	Long seek backward a specified number of seconds (default 600 seconds = 10 minutes).
235	fnMainContextMenu 	All	Pop-up the Main Context Menu.
236	fnPLContextMenu 	All	Pop-up the Playlist Context Menu.
237	fnResetBalance 	All	Reset the Audio Balance to Center.
238	fnResetPlayRate 	Media	Reset Play Rate to normal speed.
239	fnIncDerivedAR 	All	Manually increase Derived Aspect Ratio width.
240	fnDecDerivedAR 	All	Manually decrease Derived Aspect Ratio width.
241	fnScheduler 	All	Show/Hide the Schedule editor.
242	fnRename 	Media	Rename/Move the playing media or selected playlist entry.
243	fnMadVRSmoothMo 	All	Enable/Disable MadVR's smooth motion.
244	fnAutoPlayNext 	Media	Enable/Disable Auto-Play next file in the playlist.
245	fnRotateVideo 	All	Rotate the video in 90 degree increments.
246	fnFileAssociation 	All	Show the file format association dialog.
247	fnDSZoomIn 	All	DirectShow Zoom-in (only works for DirectShow based playback and may not work with all video renderers).
248	fnDSZoomOut 	All	DirectShow Zoom-out (only works for DirectShow based playback and may not work with all video renderers).
249	fnDSPanLeft 	All	DirectShow Pan-left (only works for DirectShow based playback and may not work with all video renderers).
250	fnDSPanRight 	All	DirectShow Pan-right (only works for DirectShow based playback and may not work with all video renderers).
251	fnDSPanUp 	All	DirectShow Pan-up (only works for DirectShow based playback and may not work with all video renderers).
252	fnDSPanDown 	All	DirectShow Pan-down (only works for DirectShow based playback and may not work with all video renderers).
253	fnPLEditMetaData 	All	Open meta-data editor for the currently playing media or playlist selected media.
254	fnPLAddUrl 	All	Add a media streaming URL (link) to the playlist.

Extended Functions:
Unlike the regular functions, extended functions pass an additional parameter to the function.

No.	Function	Description	Value
000	exSetAR 	Set Aspect Ratio 	0-6
001	exApplyPR 	Apply Zoom Preset 	0-9
002	exSavePR 	Save Zoom Preset 	0-9
003	exChapterTrack	Chapter/Track Selector 	0-9 (Opens chapter/track dialog with 5 seconds timeout for a second key)
004	exBlanking 	Set Blanking Preset 	0-9 (Automatically enables blanking)
005	exSetMode 	Set Playback Mode 	0-Media Mode, 1-DVD Mode, 2-Audio Mode
006	exInterface 	Toggle Interfaces
      00-Show Control Bar
 	 	 	01-Hide Control Bar
 	 	 	02-Show Playlist Editor
 	 	 	03-Hide Playlist Editor
 	 	 	04-Show Chapter/Bookmark Editor
 	 	 	05-Hide Chapter/Bookmark Editor
 	 	 	06-Set Windowed Mode
 	 	 	07-Set Zoom Mode
 	 	 	08-Set Fullscreen Mode
 	 	 	09-Show Equalizer
 	 	 	10-Hide Equalizer
 	 	 	11-Enable Pop-up OSD messages
 	 	 	12-Disable Pop-up OSD messages
007	exSetPlayRate 	Set Media Play Rate 	1-22670 (where 10000 = Standard Play)
008	exSetCustomAR 	Set Custom Aspect Ratio 	0-9 (Automatically switches AR to Custom mode)
009	exOverlayColor	Set Color Control Preset 	0-9
010	exPlayComplete	Set Playlist Complete Mode
      00-Do Nothing
 	 	 	01-Auto Rewind
 	 	 	02-Auto Replay
 	 	 	03-Close Player
 	 	 	04-Shutdown Windows
 	 	 	05-Play Next Dir File (Media Ext)
 	 	 	06-Minimize
 	 	 	07-Eject CD
 	 	 	08-Close Media
 	 	 	09-Open Media Library
 	 	 	10-Randomize & Replay
 	 	 	11-Play Next Dir File (Same Ext)
011	exDVDNumPad 	Select DVD Number Pad 	0-9
012	exOpenDrive 	Open an entire drive 	0-25 (0 = A:, 2 = C: ... 25 = Z:)
013	exSeekAhead 	Seek Ahead [n] Seconds 	1-999999999
014	exSeekBack 	Seek Back [n] Seconds 	1-999999999
015	exSeekTo 	Seek to Position [n] Seconds 	0-999999999
016	exGroupToggle 	Toggle Skin Groups 	0-1^32 (Bitmask indicating which groups to toggle, use a negative value to force the window size to remain unchanged)
017	exGroupEnable 	Enable Skin Groups 	0-1^32 (Bitmask indicating which groups to enable, use a negative value to force the window size to remain unchanged)
018	exGroupDisable	Disable Skin Groups 	0-1^32 (Bitmask indicating which groups to disable, use a negative value to force the window size to remain unchanged)
019	exGroupSet 	Set the Skin Groups Mask 	0-1^32 (Bitmask indicating the group mask, use a negative value to force the window size to remain unchanged)
020	exSetVolume 	Set the Audio Volume 	0-100 (Percentage of volume level)
021	exEjectDrive 	Eject/Insert a drive 	0-25 (drives A-Z where 0=A and 25=Z)
022	exEnableTCP 	Enable TCP/IP interface 	TCP Port number
023	exZoomTo 	Zoom Video Size (percent) 	1-1000 Zoom Video Size (percent)
024	exTransWin 	Set player Window Transparency 	1-255, where 255 = disable transparency
025	exRandomPlay 	Set Random Play ON/OFF 	0=Off, 1=On
026	exSkinTint 	Set the User Interface color Tint	RGB Integer Value (Example: "$FF0000" = Red)
027	exSkinMode 	Enable Skin-Specific Mode 	1-6, by default assigned to F4-F9 keys
028	exScheduler 	Enable/Disable the Scheduler 	0 = Disable the scheduler, 1 = Enable the scheduler
029	exPlaylistMode	Sets the 'on playlist complete' mode
      0 = Do nothing
      1 = Auto-Rewind
      2 = Auto-Replay
      3 = Close Player
      4 = Shutdown Windows
      5 = Play Next dir file (media ext)
      6 = Minimize
      7 = Eject CD
      8 = Close Media
      9 = Open Media Library
      10 = Randomize Playlist & Replay
      11 = Play Next dir file (same ext)
      12 = Play Next Random dir file (media ext)
      13= Play Next Random dir file (same ext)
030	exPartLoader 	Set the Multiple-Part file loader mode	0 = Disable the Multi-Part loader
      1 = Set Multi-Part file loader to Automatic Match
      2 = Set Multi-Part file loader to Name Masking
031	exStayOnTop 	Set 'Stay on Top' mode 	0 = Disable Stay on Top
      1 = Enable Stay on Top
033	exSlideshow 	Set image slideshow duration 	The number of seconds to display a still image, set to 0 to disable the slideshow feature.
033	exFastforward 	Fast Forward 	A value of 2500 = x2.5 fast forward rate, a positive value specifies an on/off toggle, a negative value (-2500) indicates the new value
    should be applied even if fast forward is already active.
034	exRewind 	Rewind 	A value of 2500 = x2.5 rewind rate, a positive value specifies an on/off toggle, a negative value (-2500) indicates the new value should be applied
    even if rewind is already active.
035	exSlowMotion 	Slow Motion 	A value of 500 = x0.5 slow motion rate, a positive value specifies an on/off toggle, a negative value (-500) indicates the new value should
    be applied even if slow motion is already active.
036	exDirectShowZoom	DirectShow Zoom 	A value of 100-10000 (only works for DirectShow based playback and may not work with all video renderers).
037	exDirectShowPan 	DirectShow Pan 	A value of 0-10000 (only works for DirectShow based playback and may not work with all video renderers).


Navigation Functions:
Navigation functions are used to control the Fullscreen Navigation interfaces.

No.	Function	Description
000	nvLeft 	Navigate Left
001	nvRight 	Navigate Right
002	nvUp 	Navigate Up
003	nvDown 	Navigate Down
004	nvHome 	Navigate to Top
005	nvEnd 	Navigate to Bottom
006	nvPgUp 	Navigate a Page Up
007	nvPgDn 	Navigate a Page Down
008	nvSelect 	Select/Activate
009	nvInsert 	Insert/Add
010	nvDelete 	Delete
011	nvBackspace	Back
012	nvEscape 	Escape/Close
013	nvShift 	Toggle SHIFT state
014	nvCAPSLOCK 	Toggle CAPSLOCK state

*)

END { ZoomPlayerCodes } .
